Update codeindex.yml

diff --git a/.github/workflows/richnav.yml b/.github/workflows/richnav.yml
--- a/.github/workflows/richnav.yml
+++ b/.github/workflows/richnav.yml
@@ -14,6 +14,13 @@ jobs:
       with:
         dotnet-version: 8.0.x
 
+    - name: Verify Solution File
+      run: |
+        if [ ! -f ./Everything.sln ]; then
+          echo "Solution file not found!"
+          exit 1
+        fi
+
     - name: Build with dotnet
       run: dotnet build ./Everything.sln --configuration Release /bl
 
